language: node_js
node_js:
  - "node"
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
before_script:
  - rethinkdb --daemon
  - node ./lib/nodejs --port-offset 1
  - sleep 10
after_script:
  - killall rethinkdb
notifications:
  email: false
